# Generated by Django 6.0.3 on 2026-04-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=20),
        ),
    ]
